"""initial schema

Revision ID: 4a7fe98f2db9
Revises: 
Create Date: 2026-07-26 23:23:43.368371
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a7fe98f2db9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('secret_ref', sa.String(length=128), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_accounts_email'), ['email'], unique=True)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('folders_processed', sa.Integer(), nullable=False),
    sa.Column('messages_fetched', sa.Integer(), nullable=False),
    sa.Column('messages_new', sa.Integer(), nullable=False),
    sa.Column('messages_failed', sa.Integer(), nullable=False),
    sa.Column('threads_touched', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('folder_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.Column('uid_validity', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'folder_name', name='uq_folder_account_name')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('thread_key', sa.String(length=512), nullable=False),
    sa.Column('normalized_subject', sa.String(length=998), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('client_email', sa.String(length=320), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('first_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_direction', sa.String(length=16), nullable=False),
    sa.Column('last_incoming_at', sa.DateTime(), nullable=True),
    sa.Column('last_outgoing_at', sa.DateTime(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_manager', sa.String(length=320), nullable=True),
    sa.Column('first_responder', sa.String(length=320), nullable=True),
    sa.Column('last_responder', sa.String(length=320), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('incoming_count', sa.Integer(), nullable=False),
    sa.Column('outgoing_count', sa.Integer(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('has_outgoing_attachments', sa.Boolean(), nullable=False),
    sa.Column('tech_status', sa.String(length=32), nullable=False),
    sa.Column('has_reply', sa.Boolean(), nullable=False),
    sa.Column('is_read_unanswered', sa.Boolean(), nullable=False),
    sa.Column('has_unread_incoming', sa.Boolean(), nullable=False),
    sa.Column('waiting_seconds', sa.Integer(), nullable=False),
    sa.Column('waiting_business_seconds', sa.Integer(), nullable=False),
    sa.Column('first_response_seconds', sa.Integer(), nullable=True),
    sa.Column('first_response_business_seconds', sa.Integer(), nullable=True),
    sa.Column('is_repeat_request', sa.Boolean(), nullable=False),
    sa.Column('sla_hours', sa.Float(), nullable=True),
    sa.Column('sla_exceeded', sa.Boolean(), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('responsible_party', sa.String(length=32), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('grouping_confidence', sa.Float(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('analyzed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_client_email'), ['client_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_first_message_at'), ['first_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_thread_key'), ['thread_key'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_thread_id'), ['thread_id'], unique=False)

    op.create_table('customer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fulfilled', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_requests_thread_id'), ['thread_id'], unique=False)

    op.create_table('manual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_reviews_thread_id'), ['thread_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('imap_uid', sa.Integer(), nullable=True),
    sa.Column('message_id_header', sa.String(length=998), nullable=True),
    sa.Column('in_reply_to', sa.String(length=998), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('normalized_subject', sa.String(length=998), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.Column('is_answered_flag', sa.Boolean(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('auto_headers', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('parse_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['mail_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'folder_id', 'imap_uid', name='uq_message_folder_uid')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index('ix_messages_msgid', ['message_id_header'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index('ix_messages_sent_at', ['sent_at'], unique=False)
        batch_op.create_index('ix_messages_thread', ['thread_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('attachment_category', sa.String(length=32), nullable=False),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_thread')
        batch_op.drop_index('ix_messages_sent_at')
        batch_op.drop_index(batch_op.f('ix_messages_sender_email'))
        batch_op.drop_index('ix_messages_msgid')
        batch_op.drop_index(batch_op.f('ix_messages_content_hash'))

    op.drop_table('messages')
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_reviews_thread_id'))

    op.drop_table('manual_reviews')
    with op.batch_alter_table('customer_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_requests_thread_id'))

    op.drop_table('customer_requests')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_thread_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_content_hash'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_thread_key'))
        batch_op.drop_index(batch_op.f('ix_threads_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_threads_first_message_at'))
        batch_op.drop_index(batch_op.f('ix_threads_current_status'))
        batch_op.drop_index(batch_op.f('ix_threads_client_email'))

    op.drop_table('threads')
    op.drop_table('mail_folders')
    op.drop_table('sync_runs')
    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_accounts_email'))

    op.drop_table('mail_accounts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
